version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  
  pre_build:
    commands:
      - echo Running tests...
      - python -m pytest || true
      - echo Running linting...
      - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true
  
  build:
    commands:
      - echo Build started on `date`
      - echo Collecting static files...
      - python manage.py collectstatic --noinput || true
  
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: '.'
